name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # dijalankan setiap 12 jam
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # --- BAGIAN PENTING YANG KURANG ---
    permissions:
      contents: write
    # ----------------------------------

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          # nama user github anda
          github_user_name: MSaktiGp
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # Token diperlukan di sini untuk mengambil grafik kontribusi jika profil privat
          # Jika profil publik, ini opsional tapi disarankan
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
